name: "Build CosmicKube game server"
on: [push]

jobs:
    build-server:
        name: "Build Game Server"
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                default: true
                override: true

            - name: Build
              run: |
                cd backend
                cargo build --all --release && strip target/release/cosmic_kube && mv target/release/cosmic_kube target/release/cosmic_kube_amd64
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                name: server
                path: backend/target/release/cosmic_kube_amd64
              