name: "Build CosmicKube game client"
on: push

env:
    GODOT_VERSION: 4.2.1
    EXPORT_NAME: CosmicKube
    PROJECT_PATH: game-source

jobs:
    export-web:
        name: "Export for Web"
        runs-on: ubuntu-20.04
        container:
            image: barichello/godot-ci:4.2.1
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                lfs: true
            - name: Setup
              run: |
                mkdir -v -p ~/.local/share/godot/export_templates/
                mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
            - name: Web Build
              run: |
                mkdir -v -p build/web
                cd $PROJECT_PATH
                godot --headless --verbose --export-release "Web" ../build/web/index.html 2>&1 | tee output.txt
                echo Reading build logs...
                if search="$(cat output.txt | grep 'ERROR: Project export')"
                then
                echo "Build failed!"
                exit 1
                else
                echo "Build succeeded!"
                exit 0
                fi ;
            - name: Create staticwebapp.config.json
              run: |
                cd build/
                echo ${{ vars.STATIC_WEB_APP_CONFIG }} > staticwebapp.config.json
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                name: web
                path: build/web
            
            - name: Publish to Azure Static Web Apps
              id: publishto
              uses: Azure/static-web-apps-deploy@v1
              with:
                    azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                    repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
                    action: "upload"
                    ###### Repository/Build Configurations ######
                    app_location: "build/web"
                    skip_app_build: true
                    ###### End of Repository/Build Configurations ######