name: "Build CosmicKube cache server"
on: 
    push:
        branches:
            - main
jobs:
    build-server:
        name: "Build Cache Server"
        runs-on: ubuntu-20.04
        permissions: 
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download Go
              uses: actions/setup-go@v5
              with:
                go-version: '^1.22'

            - name: Build
              run: |
                cd kube_cache
                go build && strip kube_cache
            
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                name: cache_server
                path: kube_cache/kube_cache
              
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

                # this will push the docker images to the github container registry
                # you will need to give actions permission to push there first
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v3
              with:
                context: .
                file: kube_cache/cache.Dockerfile
                push: true
                tags: |
                    ghcr.io/pilksoc/kubecache:latest
                    ghcr.io/pilksoc/kubecache:dev-${{ github.run_number }}