name: "Deploy to archive"
on:
  push:
    branches:
      - main

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: CosmicKube
  PROJECT_PATH: game-source

jobs:
  export-web:
    name: "Export for Web"
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" ../build/web/index.html 2>&1 | tee output.txt
          echo Reading build logs...
          if search="$(cat output.txt | grep 'ERROR: Project export')"
          then
          echo "Build failed!"
          exit 1
          else
          echo "Build succeeded!"
          exit 0
          fi ;
      - name: Create staticwebapp.config.json
        run: |
          cd build/web
          echo "${{ vars.STATIC_WEB_APP_CONFIG }}" > staticwebapp.config.json
          ls
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web

  deploy-to-azure:
    name: "Deploy to Azure"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web
          path: web
      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_LOGIN }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch --account-name "${{ vars.STORAGE_ACCOUNT_NAME }}" --auth-mode key -s '$web' --pattern "cosmickube/*"
            az storage blob upload-batch --account-name "${{ vars.STORAGE_ACCOUNT_NAME }}" --auth-mode key -d '$web' --destination-path cosmickube -s web

      - name: Logout from Azure CLI
        run: |
          az logout
        if: always()
